channels:
- damianavila82
- defaults
- conda-forge
- anaconda-fusion
- bobpkgs
- dsdale24
dependencies:
- cython=0.26=py36_0
- pystan=2.15.0.1=py36_0
- toolz=0.8.2=py36_0
- rise=5.0.0=py36_0
- appnope=0.1.0=py36_0
- bleach=1.5.0=py36_0
- click=6.7=py36_0
- cycler=0.10.0=py36_0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- flask=0.12.2=py36_0
- freetype=2.5.5=2
- hdf5=1.8.17=2
- html5lib=0.999=py36_0
- icu=54.1=0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- itsdangerous=0.24=py36_0
- jbig=2.1=0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- joblib=0.11=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libgpuarray=0.6.8=0
- libpng=1.6.27=0
- libprotobuf=3.2.0=0
- libtiff=4.0.6=3
- mako=1.0.6=py36_0
- markupsafe=0.23=py36_2
- matplotlib=2.0.2=np112py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py36_3
- mpmath=0.19=py36_1
- nbconvert=5.2.1=py36_0
- nbformat=4.3.0=py36_0
- nose=1.3.7=py36_1
- notebook=5.0.0=py36_0
- numexpr=2.6.2=np112py36_0
- numpy=1.12.1=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pandas=0.20.2=np112py36_0
- pandocfilters=1.4.1=py36_0
- path.py=10.3.1=py36_0
- patsy=0.4.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.14=py36_0
- protobuf=3.2.0=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.2.0=py36_0
- pygpu=0.6.8=py36_0
- pymc3=3.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- pytables=3.3.0=np112py36_0
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=2
- qtconsole=4.3.0=py36_0
- readline=6.2=2
- scikit-learn=0.18.2=np112py36_0
- scipy=0.19.1=np112py36_0
- seaborn=0.7.1=py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np112py36_0
- sympy=1.1.1=py36_0
- tensorflow=1.1.0=np112py36_0
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- theano=0.9.0=py36_0
- tk=8.5.18=0
- tornado=4.5.1=py36_0
- tqdm=4.14.0=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- werkzeug=0.12.2=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - edward==1.3.3
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - maxentropy==0.2.3
  - prompt-toolkit==1.0.14
  - tables==3.3.0

